version: '3.9'
services:
  flask:
    build: .
    image: wotsyula/flask-scraper
    environment:
      - PYTHONUNBUFFERED=0
      - DATABASE_URI=postgresql://postgres:postgres@postgres/postgres
      - SELENIUM_URI=http://selenium:4444
    ports:
      - "80:5000"
    depends_on:
      - selenium
  selenium:
    build:
      context: ./composer
      dockerfile: standalone-chrome
    image: wotsyula/selenium:latest
    ports:
      - "5900:5900"
    shm_size: 256M
