version: '3.9'
services:
  flask:
    build: .
    image: wotsyula/flask-scraper
    volumes:
      - profile:/usr/src/Profile
    environment:
      - PYTHONUNBUFFERED=0
      - DATABASE_URI=postgresql://postgres:postgres@postgres/postgres
      - SELENIUM_URI=http://selenium:4444
    ports:
      - "80:5000"
    depends_on:
      - selenium
  selenium:
    build:
      context: ./composer
      dockerfile: standalone-chrome
    image: wotsyula/selenium:latest
    volumes:
      - profile:/home/seluser/userdata
    environment: 
      - SE_NODE_SESSION_TIMEOUT=60
      - SE_NODE_MAX_SESSIONS=16
      - SCREEN_DEPTH=24
      - SCREEN_HEIGHT=768
      - SCREEN_WIDTH=1366
    ports:
      - "5900:5900"
    shm_size: 256M
volumes:
  profile
