version: '3.9'
services:
  flask:
    build: .
    environment:
      - PYTHONUNBUFFERED=0
      - DATABASE_URI=postgresql://postgres:postgres@postgres/postgres
      - SELENIUM_URI=http://selenium:4444
    ports:
      - "80:5000"
    depends_on:
      - selenium
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:latest
    environment: 
      - SE_NODE_SESSION_TIMEOUT=30
      - SE_NODE_MAX_SESSIONS=16
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    ports:
      - "5900:5900"
    shm_size: 256M
