export const ActionTypes = {
    FIND_PEOPLE:            'FIND_PEOPLE',
    FIND_PEOPLE_CANCEL:     'FIND_PEOPLE_CANCEL',
    FIND_PEOPLE_STATUS:     'FIND_PEOPLE_STATUS',
    FIND_PEOPLE_RESULTS:    'FIND_PEOPLE_RESULTS',
}
